# Generated by Django 3.2.5 on 2022-01-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/%d/')),
                ('quote_title', models.TextField()),
                ('quote_description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
            ],
        ),
    ]
