# Generated by Django 5.2.2 on 2025-06-07 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_remove_orderitem_description_orderitem_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_title',
            field=models.TextField(),
        ),
    ]
