# Generated by Django 5.1.7 on 2025-06-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20231116_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('expiring_date', models.DateField()),
                ('domain_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hosting_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostings', to='customer.customer')),
            ],
        ),
    ]
