# Generated by Django 4.2.23 on 2025-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_hosting_created_at_hosting_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
