# Generated by Django 4.2.23 on 2025-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_hosting_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='notified',
        ),
        migrations.AddField(
            model_name='hosting',
            name='last_notified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
