# Generated by Django 4.2.23 on 2025-06-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_remove_hosting_notified_hosting_last_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='registration_date',
        ),
    ]
