# Generated by Django 4.2.23 on 2025-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_remove_hosting_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='next_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
