# Generated by Django 3.2.5 on 2022-01-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('amount_inwords', models.CharField(max_length=200)),
                ('amount_infigure', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
