# Generated by Django 4.2.23 on 2025-06-13 10:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20231116_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter WhatsApp number with country code.', max_length=128, null=True, region='TZ'),
        ),
    ]
