# Generated by Django 4.0.4 on 2022-05-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('hosting', 'Hosting'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
