# Generated by Django 4.0.4 on 2022-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
