# Generated by Django 4.0.4 on 2022-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
