# Generated by Django 4.0.4 on 2022-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(default='others', max_length=10),
        ),
    ]
