# Generated by Django 3.2 on 2023-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('formal', 'Formal')], default='proforma', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('hosting', 'Hosting'), ('others', 'Others')], default='others', max_length=10),
        ),
    ]
