# Generated by Django 3.1.7 on 2021-03-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
    ]
