# Generated by Django 3.2 on 2023-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20230718_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('formal', 'Formal')], default='formal', max_length=10),
        ),
    ]
