# Generated by Django 3.1.7 on 2021-03-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_orderitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/%d/')),
                ('quote_title', models.TextField()),
                ('quote_description', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.customer')),
            ],
        ),
    ]
