# Generated by Django 3.2 on 2023-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('formal', 'Formal')], default='proforma', max_length=10),
        ),
    ]
