# Generated by Django 3.1.7 on 2021-03-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
